### ISSUE TITLE
LoadError when using gem

### ISSUE THREAD

**Issue by johntopleyons** [alphagov/notifications-ruby-client#16]
Hi,

I get a load error when attempting to use the **notifications-ruby-client** gem:

```
$ irb
>> require 'notifications-ruby-client'
LoadError: cannot load such file -- notifications-ruby-client
	from /usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```

Operating systems: CentOS 7, macOS Sierra 10.12
Ruby versions: ruby 2.4.0preview1 (2016-06-20 trunk 55466) [x86_64-linux], ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

**Comment by servingUpAces** [comment]
You need to install the notifications-ruby-client gem first from the command line.
> gem install notifications-ruby-client. 
Then you can use the client from irb> require 'notifications/client'
Please refer to the read me of this repo.

**Comment by johntopleyons** [comment]
Sorry, I already had the gem installed but got caught out by this change: https://github.com/alphagov/notifications-ruby-client/commit/71dee
