### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by tobyprivett** [alphagov/notifications-ruby-client#23]
The instruction say:
`client = Notifications::Client.new(api_key)`

But this returns:
`ArgumentError: wrong number of arguments (given 1, expected 2..3)`

The Speaker class expects a service_id and an api_secret. Can you clarify that the api_secret is the same as the API key that can be configured through the Notify admin console?

**Comment by pixeltrix** [comment]
@tobyprivett I've replied to your support request - can you confirm that you're using the latest version (1.1.2) of the client gem?

**Comment by tobyprivett** [comment]
@pixeltrix I installed the gem a short while ago and it was V1.0.0. I've now upgraded to 1.1.2 and the issue is resolved. Thanks for your prompt response!
